### ISSUE TITLE
Metrics correspond to HystrixCommand not displayed in Hystrix Dashboard

### ISSUE THREAD

**Issue by tuan3w** [vert-x3/vertx-circuit-breaker#11]
Hello,
I follow the tutorial at http://vertx.io/docs/vertx-circuit-breaker/java/ to know how to use hystrix with vertx. But as I check, only metrics by Vertx Circruit Breaker are displayed in Hystrix Dashboard while metrics corresponding to HystrixCommand aren't. Am I wrong at something? Here is the sample code:
https://gist.github.com/tuan3w/de7cbc82572bbdf235bbb326becb21c8 .
Thanks

**Comment by cescoffier** [comment]
Yes, only circuit breaker metrics are exposed. If your command was executed by a circuit breaker you would get its statistics as part of the exposed metrics.
