### ISSUE TITLE
Implement retry with exponential back-off

### ISSUE THREAD

**Issue by inikolaev** [vert-x3/vertx-circuit-breaker#21]
Looking at the source code and available configuration options it looks like retry is being executed immediately right now, but it's usually recommended to retry with exponential backoff (with optional jitter) as to not overload failing host even more.

I could implement this feature, but would require some guidance on how to implement it correctly with VertX.

**Comment by vietj** [comment]
I think that the user should be able to provide a function that returns the time to wait after the try. The default function returns `0` and we can provide one with exp backoff.

```
// Wait 10 ms
breaker.retryStrategy(retries -> 10);

// Wait (retries * 10) ms 
breaker.retryStrategy(retries -> retries * 10);
```

**Comment by inikolaev** [comment]
Should this `retryStrategy` method be specified as an option or should it be a method of a breaker?
The only benefit of having it a method of a breaker that I can see is to be able to modify it at run time, but I'm not sure how valuable that is though.

**Comment by vietj** [comment]
I think that it can be constant but then you can have a function you can dynamically parameter at runtime:

```
breaker.retryStrategy(retries -> retries * timeMs);
```

where `timeMs` can be changed.

**Comment by inikolaev** [comment]
Not really, if I remember correctly all variables passed to the lambda function have to be effectively final. Unless it's something like a container, e.g. `AtomicInteger`.

I will proceed with some solution and then we can refine it when I submit PR.

**Comment by cescoffier** [comment]
Fied in master, closing issue.
