### ISSUE TITLE
Circuit breaker failures never count down..

### ISSUE THREAD

**Issue by Alars-ALIT** [vert-x3/vertx-circuit-breaker#24]
.. this leads to the scenario that one failure can trip the circuit, even if no failures has occured for days and .setMaxFailures is set to a large number. 

I assume this isn't a desired scenario for most use cases? Hystrix solves this by keeping the failure count in an rolling window.

**Comment by cescoffier** [comment]
Sounds like a critical bug, do you have a reproducer?

**Comment by Alars-ALIT** [comment]
Any news on this? I did add a pull request a month ago that reproduces this with a test and includes a solution .

https://github.com/vert-x3/vertx-circuit-breaker/pull/25
