### ISSUE TITLE
High CPU usage when circuit is open under heavy load

### ISSUE THREAD

**Issue by epalumbo** [vert-x3/vertx-circuit-breaker#28]
We've found that exceptions raised due to open circuit state end up overloading CPUs. In cases where application is handling a huge amount of errors and a circuit opens, this plain "RuntimeException" is used to fail the operation future: https://github.com/vert-x3/vertx-circuit-breaker/blob/master/src/main/java/io/vertx/circuitbreaker/impl/CircuitBreakerImpl.java#L304
We've discovered that this high CPU usage could be avoided if the exception does not have the "writableStackTrace" flag as true, like "NoStackTraceThrowable" does. Also, it might be convenient to use a custom exception for this scenario, probably a "RuntimeException" subclass to keep backward compatibility.

**Comment by epalumbo** [comment]
Thanks Clement for the ultra quick fix.

We could see that the above mentioned `RuntimeException` was replaced by the `NoStackTraceThrowable`, which is not a subclass of `RuntimeException`. If a client handles circuit failures testing against `RuntimeException` or maybe `Exception`, it will probably stop working. 

I would like to know if there is a reason to avoid creating a specific exception for this purpose, or maybe for more general purposes but still specific to this library. For instance, Hystrix defines [three high-level exceptions](https://netflix.github.io/Hystrix/javadoc/com/netflix/hystrix/exception/package-summary.html) to handle all kinds of circuit-breaker-handled failures.

And again, thank you for the quick response.

**Comment by cescoffier** [comment]
No, you are right, we should create a specific Exception extending RuntimeException for this use case. 

Reopening the issue.

**Comment by epalumbo** [comment]
That's ok, thank you very much for the PR @cescoffier.

**Comment by cescoffier** [comment]
Closing the issue, fixed in master.
