### ISSUE TITLE
Failure in Travis

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-circuit-breaker#31]
https://travis-ci.org/vert-x3/vertx-circuit-breaker/jobs/461176637

```
Tests in error: 
  HystrixMetricEventStreamTest.test Â» IllegalState Response is closed
```

**Comment by cescoffier** [comment]
I will have a look.

However, hystrix being almost retired, we may want to drop this feature (exposing metrics using the Hystrix metrics) totally in V4. WDYT?

**Comment by vietj** [comment]
I think we should figure out if that's used or not in practice, then it makes more sense to remove it.

**Comment by cescoffier** [comment]
Well, there is nothing consuming this data anymore.

**Comment by cescoffier** [comment]
Issue fixed in master.
