### ISSUE TITLE
Duplicate Strings from CircuitBreakerMetrics#toJson waste heap memory

### ISSUE THREAD

**Issue by Emmeral** [vert-x3/vertx-circuit-breaker#49]
### Version

3.9.2

### Context

A heap dump of our application showed that there are suspiciously many dublicated Strings related to the vert.x circuit breaker (see screenshot)
![image](https://user-images.githubusercontent.com/35600952/103901765-dc6ad600-50f9-11eb-9a44-e2908089d1d6.png)
 
This seems to be related to the fact that the different names of the different metrics are not constant at compile time but rather dynamically generated at every `toJson()` call of `CircuitBreakerMetrics`. This call is performed periodically in `CircuitBreakerImpl`.. This probably leads to the duplicated Strings in the heap, as every call produces another String Object with the same content, but with a different memory location.

This can probably be fixed by turning the names of the different metrices into compile time constants or calling `String#intern()` at each creation.

### Do you have a reproducer?

No

### Steps to reproduce

1. Have a circuit breaker in your application
2. Let it run for a long time
3. Analyze the heap (for example with [JXRay](https://jxray.com/))

### Extra
Used Java 8

**Comment by vietj** [comment]
@Emmeral do you mind providing a patch for this ?

**Comment by Emmeral** [comment]
I think I can try.
From where shall I branch off? The relevant code seems to be identical in the 3.9 and master branch.

**Comment by Emmeral** [comment]
@vietj I created a PR to the 3.9 branch (#50)

**Comment by vietj** [comment]
thank @Emmeral I'll try cherry pick for master

**Comment by vietj** [comment]
I cherry picked to master and set the fix version to 4.0.1 , the issue fixed in 3.9 will appear as a PR.
