### ISSUE TITLE
Event bus notifications are enabled and clustered by default

### ISSUE THREAD

**Issue by slinkydeveloper** [vert-x3/vertx-circuit-breaker#51]
The EventBus notifications are enabled by default, causing quite some unnecessary traffic on the event bus. We should probably have them optional

**Comment by vladoltean** [comment]
In the meanwhile, anyone trying to disable them can set the address to null to avoid sending those notifications. (see [this](https://github.com/vert-x3/vertx-circuit-breaker/blob/1114bc1f357b4015a02c7ff3d5226f5a6f801743/src/main/java/io/vertx/circuitbreaker/impl/CircuitBreakerImpl.java#L159))

`new CircuitBreakerOptions().setNotificationAddress(null);`
