### ISSUE TITLE
Metrics published by vertx to hystrix dashboard isn't consistent with hystrix

### ISSUE THREAD

**Issue by kennedyoliveira** [vert-x3/vertx-circuit-breaker#6]
Hello,

i noticed something and don't know if this is the intended behavior, but the metrics published by the `HystrixMetricHandler` when using the circuit breaker isn't consistent with hystrix, for example the request count sent is a global one, and in the hystrix is the count for the rolling window, so we can't measure the request per second, since the vertx will always be increasing.

In the example below, i'm showing the same thing executed by hystrix and vertx-circuit-breaker, 4 requests per second, all on the same verticle, same jvm, same everything, and on hystrix we can see it accurately showing 4.0 req/s, but the vertx shows 79.1 req/s, and the success count is different too:
![screenshot from 2017-04-10 12 11 31](https://cloud.githubusercontent.com/assets/7723330/24868557/c7db59b6-1de6-11e7-9596-d198047d570f.png)

If this is not the intended behavior, i can try to write a PR to make it more consistent.

By the way, the test i did is avaliable here: [Example](https://gist.github.com/kennedyoliveira/24e5827edbc2185b396c08faa67a5269)

You can get a running hystrix-dashboard easy using [standalone-hystrix-dashboard](https://github.com/kennedyoliveira/standalone-hystrix-dashboard)

**Comment by kennedyoliveira** [comment]
Complementing, in the [CircuitBreakerMetrics](https://github.com/vert-x3/vertx-circuit-breaker/blob/master/src/main/java/io/vertx/circuitbreaker/impl/CircuitBreakerMetrics.java#L221) the percentages are being calculated against the global request count, and should be against the rolling window too.

**Comment by cescoffier** [comment]
Thanks, that's definitely bugs.

**Comment by cescoffier** [comment]
@kennedyoliveira do you have the list of inconsistencies:

* request count should be the rolling window one.
* global request count should be the rolling window one.
* request/second not computed correctly

**Comment by cescoffier** [comment]
@kennedyoliveira I've started making progress in: https://github.com/vert-x3/vertx-circuit-breaker/tree/fix-hystrix-metrics.

Can you have a look ?

**Comment by kennedyoliveira** [comment]
@cescoffier thanks for the reply, and sorry for taking to long to reply you, sure i'll look and give a feedback.

**Comment by cescoffier** [comment]
Just made some more changes. I believe it's almost complete.

**Comment by cescoffier** [comment]
I've opened the PR #8.

**Comment by cescoffier** [comment]
Fixed by #8
