### ISSUE TITLE
how to use it  in a cluster？

### ISSUE THREAD

**Issue by qsqiushi** [vert-x3/vertx-circuit-breaker#66]
Every time the circuit state changes, an event can be published on the event bus.  but，How to work together in different instances？

**Comment by gaol** [comment]
First of all, I encourage you asking questions either via [user group](https://groups.google.com/forum/?fromgroups#!forum/vertx) or [discord](https://discord.gg/6ry7aqPWXy).

For this question, I think you are looking for an option to be able to publish the event to remote vert.x instance, and you can use [CircuitBreakerOptions.setNotificationLocalOnly(false)](https://github.com/vert-x3/vertx-circuit-breaker/blob/4.3.8/src/main/java/io/vertx/circuitbreaker/CircuitBreakerOptions.java#L272) for this purpose.

**Comment by qsqiushi** [comment]
> 

I have used  CircuitBreakerOptions.setNotificationLocalOnly(false) And  defined a consumer
But it is difficult to synchronize the state and failure count

**Comment by gaol** [comment]
If you have a reproducer, it is easier for us to spot on. :)

**Comment by tsegismont** [comment]
Notifications are no longer enabled by default (see #57).

To enable notifications, see: https://vertx.io/docs/vertx-circuit-breaker/java/#_event_bus_notification
