### ISSUE TITLE
Exponential delay RetryPolicy fails with IllegalArgumentException when retryCount==63

### ISSUE THREAD

**Issue by dfeist** [vert-x3/vertx-circuit-breaker#70]
### Version

4.36

### Context

This is caused by the shift operation used for the exponential delay which results in a value of `0` after 63 retries.  This cannot simply be resolved by simply using `delay<0=` as this results in the exponential delay restarting from initialDelay.

```
      long delay = initialDelay * (1L << retryCount);
      return random.nextLong(0, delay < 0 ? maxDelay : min(maxDelay, delay));
```

**Comment by tsegismont** [comment]
Cannot reproduce. Please reopen if you can provide stacktrace and values which allow to reproduce.
